package lk.ijse.ticket_ticket_service.util.location;

public enum Location {
    KOTTAWA, KAHATHUDUWA, GELANIGAMA, DODANGODA, WELIPENNA, KURUNDUGAHAHETEKMA, BADDEGAMA, PINNADUWA, IMADUWA, KOKMADUWA, GODAGAMA, ATHURUGIRIYA, KADAWATHA, KERAWALAPITIYA, PELIYAGODA, JAELA, KATUNAYAKE, MIRIGAMA

}
